version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:12.10-alpine
    expose:
      - 5432
    ports:
      - "5431:5432"
    volumes:
      - ./.docker/postgresql/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
